### ISSUE TITLE
Context product missing from Working directory

### ISSUE THREAD

**Issue by matthewtiscareno** [NASA-PDS/EdWG#55]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

As I was looking for particular context products that I would want to address, I noticed that `spacecraft.co` (that is, Cassini) is in the `instrument_host` directory but not in the `instrument_host/working` directory. 

I imagine that EN will want to not only move this to the `working` directory but also make the updates that it has made to other context products in the `working` directory.  I might also suggest that EN check whether any other context products are missing, since I only caught this by a random spot check.

**Comment by jordanpadams** [comment]
@matthewtiscareno good catch. Not sure how that happened. I will review and see what happened there and update.

**Comment by c-suh** [comment]
@jordanpadams what directory is this? Information to test this for I&T, please and thank you.

**Comment by jordanpadams** [comment]
@c-suh skip. anything in this repo can be skipped.
